#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'puzzlebot-gazebo','console_scripts','tf_map'
__requires__ = 'puzzlebot-gazebo'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('puzzlebot-gazebo', 'console_scripts', 'tf_map')()
    )
