controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - base_to_left_w
      - base_to_right_w
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort

